import '../models/models.dart';

class MockData {
  static List<GroupBuyPost> groupBuyPosts = [
    GroupBuyPost(
      id: '1',
      title: '코스트코 두루마리 화장지 30롤',
      category: '생활용품',
      imageUrl: '',
      totalPrice: 38000,
      unitPrice: 9500,
      maxParticipants: 4,
      currentParticipants: 3,
      walkMinutes: 5,
      location: '안암동',
      authorName: '이예주',
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      isDelivery: false,
    ),
    GroupBuyPost(
      id: '2',
      title: '굽네치킨 반반 4인분 소분 구해요',
      category: '배달음식',
      imageUrl: '',
      totalPrice: 32000,
      unitPrice: 8000,
      maxParticipants: 4,
      currentParticipants: 2,
      walkMinutes: 8,
      location: '안암동',
      authorName: '김보민',
      createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
      isDelivery: true,
    ),
    GroupBuyPost(
      id: '3',
      title: '올리브유 5L 대용량 나눠요',
      category: '식료품',
      imageUrl: '',
      totalPrice: 24000,
      unitPrice: 6000,
      maxParticipants: 4,
      currentParticipants: 1,
      walkMinutes: 12,
      location: '종암동',
      authorName: '양재인',
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      isDelivery: false,
    ),
    GroupBuyPost(
      id: '4',
      title: '맥도날드 10피스 치킨너겟 소분',
      category: '배달음식',
      imageUrl: '',
      totalPrice: 12000,
      unitPrice: 3000,
      maxParticipants: 4,
      currentParticipants: 4,
      walkMinutes: 3,
      location: '안암동',
      authorName: '이영지',
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      isDelivery: true,
    ),
  ];

  static List<ExchangePost> exchangePosts = [
    ExchangePost(
      id: '1',
      title: '라면 5봉지 ↔ 즉석밥 5개',
      description: '신라면 5봉지 있어요. 즉석밥이나 계란으로 바꿀 의향 있으신 분!',
      offerItem: '신라면 5봉지',
      wantItem: '즉석밥 5개',
      imageUrl: '',
      authorName: '이예주',
      location: '안암동',
      walkMinutes: 5,
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      status: ExchangeStatus.open,
    ),
    ExchangePost(
      id: '2',
      title: '샴푸 ↔ 바디워시',
      description: '팬틴 샴푸 반통 남았는데 바디워시로 교환 원해요',
      offerItem: '팬틴 샴푸 반통',
      wantItem: '바디워시 아무거나',
      imageUrl: '',
      authorName: '김보민',
      location: '안암동',
      walkMinutes: 7,
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      status: ExchangeStatus.open,
    ),
    ExchangePost(
      id: '3',
      title: '계란 6개 ↔ 우유 1L',
      description: '계란 6개 드릴게요. 우유 필요해요',
      offerItem: '계란 6개',
      wantItem: '우유 1L',
      imageUrl: '',
      authorName: '양재인',
      location: '종암동',
      walkMinutes: 10,
      createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
      status: ExchangeStatus.chatting,
    ),
  ];

  static List<RoomReview> roomReviews = [
    RoomReview(
      id: '1',
      buildingName: '안암동 원룸 A동',
      address: '서울 성북구 안암동 3가 12-5',
      rating: 3.5,
      summaryText: '층간소음은 꽤 있지만 집주인은 연락이 잘 돼요. 보일러가 좀 오래됨.',
      tags: [
        ReviewTag(label: '층간소음 있음', isPositive: false),
        ReviewTag(label: '집주인 친절', isPositive: true),
        ReviewTag(label: '교통 편리', isPositive: true),
        ReviewTag(label: '보일러 오래됨', isPositive: false),
      ],
      reviewCount: 4,
      isUnlocked: true,
      unlockPoints: 50,
      authorName: '이예주',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
    RoomReview(
      id: '2',
      buildingName: '안암동 신축 원룸',
      address: '서울 성북구 안암로 143',
      rating: 4.5,
      summaryText: '22년 준공 신축이라 깔끔해요. 수압도 세고 방음도 좋은 편.',
      tags: [
        ReviewTag(label: '신축 깔끔', isPositive: true),
        ReviewTag(label: '수압 좋음', isPositive: true),
        ReviewTag(label: '방음 양호', isPositive: true),
        ReviewTag(label: '관리비 비쌈', isPositive: false),
      ],
      reviewCount: 7,
      isUnlocked: false,
      unlockPoints: 50,
      authorName: '김보민',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    RoomReview(
      id: '3',
      buildingName: '종암동 반지하 원룸',
      address: '서울 성북구 종암로 77',
      rating: 2.0,
      summaryText: '결로 심함. 벽지에 곰팡이 생겼어요. 집주인 연락 안 받음.',
      tags: [
        ReviewTag(label: '결로/곰팡이', isPositive: false),
        ReviewTag(label: '집주인 연락 안 됨', isPositive: false),
        ReviewTag(label: '임대료 저렴', isPositive: true),
      ],
      reviewCount: 3,
      isUnlocked: false,
      unlockPoints: 30,
      authorName: '양재인',
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
    ),
  ];

  static List<GatherPost> gatherPosts = [
    GatherPost(
      id: '1',
      title: '오늘 저녁 혼밥 메이트 구해요',
      description: '혼자 먹으려니 쓸쓸해서요. 근처 분식집에서 같이 먹어요!',
      emoji: '🍜',
      place: '안암동 맛집 분식집',
      meetTime: DateTime.now().add(const Duration(hours: 2)),
      maxMembers: 3,
      currentMembers: 1,
      authorName: '이예주',
      genderFilter: GenderFilter.any,
      ageFilter: AgeFilter.twenties,
      createdAt: DateTime.now().subtract(const Duration(minutes: 20)),
    ),
    GatherPost(
      id: '2',
      title: '아침 집 앞 산책 파트너',
      description: '매일 아침 7시에 고려대 운동장 한 바퀴. 같이 걸어요 :)',
      emoji: '🚶',
      place: '고려대학교 운동장',
      meetTime: DateTime.now().add(const Duration(hours: 13)),
      maxMembers: 4,
      currentMembers: 2,
      authorName: '김보민',
      genderFilter: GenderFilter.any,
      ageFilter: AgeFilter.any,
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
    ),
    GatherPost(
      id: '3',
      title: '편의점 야식 같이 먹을 분',
      description: 'GS25에서 1+1 행사 중. 같이 야식 먹어요!',
      emoji: '🍟',
      place: '안암동 GS25',
      meetTime: DateTime.now().add(const Duration(hours: 1)),
      maxMembers: 2,
      currentMembers: 2,
      authorName: '이영지',
      genderFilter: GenderFilter.femaleOnly,
      ageFilter: AgeFilter.twenties,
      createdAt: DateTime.now().subtract(const Duration(minutes: 10)),
    ),
  ];

  static List<ChatRoom> chatRooms = [
    ChatRoom(
      id: '1',
      title: '코스트코 화장지 공동구매',
      lastMessage: '내일 오후 3시에 만나요!',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 5)),
      unreadCount: 2,
      avatarEmoji: '🧻',
      type: ChatRoomType.groupBuy,
      members: [],
    ),
    ChatRoom(
      id: '2',
      title: '라면↔즉석밥 교환',
      lastMessage: '제가 먼저 갖다 드릴게요',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 30)),
      unreadCount: 0,
      avatarEmoji: '🍜',
      type: ChatRoomType.exchange,
      members: [],
    ),
    ChatRoom(
      id: '3',
      title: '오늘 저녁 혼밥 메이트',
      lastMessage: '7시에 분식집 앞에서 봬요~',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 1)),
      unreadCount: 1,
      avatarEmoji: '🍽️',
      type: ChatRoomType.gather,
      members: [],
    ),
  ];

  static List<AppNotification> notifications = [
    AppNotification(
      id: '1',
      type: NotificationType.groupBuy,
      title: '🛒 공동구매 마감 임박!',
      body: '코스트코 두루마리 화장지 — 1자리 남았어요. 지금 참여하세요!',
      createdAt: DateTime.now().subtract(const Duration(minutes: 10)),
    ),
    AppNotification(
      id: '2',
      type: NotificationType.exchange,
      title: '🔄 교환 요청이 왔어요',
      body: '김보민님이 "라면 5봉지 ↔ 즉석밥" 교환을 제안했어요.',
      createdAt: DateTime.now().subtract(const Duration(minutes: 35)),
      isRead: true,
    ),
    AppNotification(
      id: '3',
      type: NotificationType.gather,
      title: '👥 모임 정원이 찼어요',
      body: '"오늘 저녁 혼밥 메이트" 모임이 마감됐어요.',
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
    ),
    AppNotification(
      id: '4',
      type: NotificationType.review,
      title: '⭐ 리뷰 작성 포인트 지급',
      body: '안암동 원룸 A동 리뷰 작성 완료! +30P가 적립됐어요.',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      isRead: true,
    ),
    AppNotification(
      id: '5',
      type: NotificationType.system,
      title: '🏠 같이삽시다 업데이트',
      body: '새로운 기능이 추가됐어요. 원룸 리뷰에서 포인트를 더 쉽게 모을 수 있어요!',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      isRead: true,
    ),
  ];
}
