// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGuoLZUR8mbRXouCpMt5ceELdyMEvYa8E',
    appId: '1:787164281308:web:f0b2d98e3471e715ec7719',
    messagingSenderId: '787164281308',
    projectId: 'gatchi-sapsida',
    authDomain: 'gatchi-sapsida.firebaseapp.com',
    storageBucket: 'gatchi-sapsida.firebasestorage.app',
    measurementId: 'G-3LKXMY1GN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74_6jO6Pjzrnb5NEsco1Zfwg7FHk8n14',
    appId: '1:787164281308:android:9245e7b43bbfa344ec7719',
    messagingSenderId: '787164281308',
    projectId: 'gatchi-sapsida',
    storageBucket: 'gatchi-sapsida.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA66mlEnEsLMuxhiLLaJedNBtYzfp3ZAtc',
    appId: '1:787164281308:ios:029bf01157b8e1eeec7719',
    messagingSenderId: '787164281308',
    projectId: 'gatchi-sapsida',
    storageBucket: 'gatchi-sapsida.firebasestorage.app',
    iosBundleId: 'com.example.live',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA66mlEnEsLMuxhiLLaJedNBtYzfp3ZAtc',
    appId: '1:787164281308:ios:029bf01157b8e1eeec7719',
    messagingSenderId: '787164281308',
    projectId: 'gatchi-sapsida',
    storageBucket: 'gatchi-sapsida.firebasestorage.app',
    iosBundleId: 'com.example.live',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGuoLZUR8mbRXouCpMt5ceELdyMEvYa8E',
    appId: '1:787164281308:web:28af7c41987ced9fec7719',
    messagingSenderId: '787164281308',
    projectId: 'gatchi-sapsida',
    authDomain: 'gatchi-sapsida.firebaseapp.com',
    storageBucket: 'gatchi-sapsida.firebasestorage.app',
    measurementId: 'G-JRED3WGQW0',
  );
}
